package:
  name: xxmotif
  version: 1.6

source:
  git_url: git@bitbucket.org:croth1/xxmotif.git
  git_rev: 1c27efe0341d4

build:
  number: 0

requirements:
  build:
    - cmake
    - gcc
    - libgcc

  run:
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/bin/XXmotif
